### ISSUE TITLE
¿Cómo levantan el proyecto?

### ISSUE THREAD

**Issue by rodowi** [opintel/clima#3]
No veo taskrunner como Gruntfile o gulp, es totalmente estático? cómo procesan los assets?

**Comment by netosw** [comment]
Es totalmente estático

On Friday, 4 December 2015, rodowi <notifications@github.com> wrote:

> No veo taskrunner como Gruntfile o gulp, es totalmente estático? cómo
> procesan los assets?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opintel/clima/issues/3>.
>


-- 

Ernesto Galindo Rojo.

**Comment by netosw** [comment]
levantamos un server local y listo

**Comment by rodowi** [comment]
cómo levantan el server local? python -m SimpleHttpServer?

**Comment by netosw** [comment]
si exacto, así no deberías tener ningun problema
