### ISSUE TITLE
Revamping the treemap

### ISSUE THREAD

**Issue by rodowi** [opintel/clima#6]
Algo así, algo bien :trollface:

http://www.nytimes.com/packages/html/newsgraphics/2011/0119-budget/

- [x] No traumarnos con los labels
- [x] Aprovechar el hover
- [x] O truncar títulos o eliminarlos

**Comment by netosw** [comment]
Si exacto, algo justo como eso

On Friday, 4 December 2015, rodowi <notifications@github.com> wrote:

> Algo así, algo bien:
>
> http://www.nytimes.com/packages/html/newsgraphics/2011/0119-budget/
>
>    - No traumarnos con los labels
>    - Aprovechar el hover
>    - O truncar títulos o eliminarlos
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opintel/clima/issues/6>.
>


-- 

Ernesto Galindo Rojo.

**Comment by rodowi** [comment]
Es mucho rollo truncar labels, porque rect, g, text aparentemente no tienen soporte. Hay un hack por ahí de un foreignObject. Pero creo que no vale la pena ahorita en las prisas. IMHO lo podemos dejar como nice-to-have en el backlog.

http://stackoverflow.com/questions/11023417/clip-svg-text-to-width-of-rectangle-in-a-d3-treemap

ForeignObject
- http://www.billdwhite.com/wordpress/2013/08/15/d3-treemap-label-truncation/
- https://gist.github.com/billdwhite/6243279

**Comment by netosw** [comment]
Ok, creo que por el constraint de tiempo deberíamos dejarlo como NTH

On Friday, 4 December 2015, rodowi <notifications@github.com> wrote:

> Es mucho rollo truncar labels, porque rect, g, text aparentemente no
> tienen soporte. Hay un hack por ahí de un foreignObject. Pero creo que no
> vale la pena ahorita en las prisas. IMHO lo podemos dejar como nice-to-have
> en el backlog.
>
>
> http://stackoverflow.com/questions/11023417/clip-svg-text-to-width-of-rectangle-in-a-d3-treemap
>
> ForeignObject
>
>    -
>    http://www.billdwhite.com/wordpress/2013/08/15/d3-treemap-label-truncation/
>    - https://gist.github.com/billdwhite/6243279
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opintel/clima/issues/6#issuecomment-162135581>.
>


-- 

Ernesto Galindo Rojo.

**Comment by rodowi** [comment]
El #9 resuelve una parte de los labels. IMHO es nuestra mejor opción.

**Comment by netosw** [comment]
Agreed, excelente!

On Friday, 4 December 2015, rodowi <notifications@github.com> wrote:

> El #9 <https://github.com/opintel/clima/pull/9> resuelve una parte de los
> labels. IMHO es nuestra mejor opción.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opintel/clima/issues/6#issuecomment-162137825>.
>


-- 

Ernesto Galindo Rojo.

**Comment by rodowi** [comment]
Closed by #9
